### ISSUE TITLE
批量插入引发"java.lang.NullPointerException" [50000-0]

### ISSUE THREAD

**Issue by quangz1031** [lealone/Lealone#122]
使用sqlshell批量插入数据后，出现异常"java.lang.NullPointerException" [50000-0]
为了复现该问题， 我修改了org.lealone.test.runmode.RunModeTest.CrudTest的insert方法中的循环次数
```java
for (int j = 0; j < 50 * 100; j++) {
```
问题复现
```java
org.lealone.common.exceptions.DbException: General error: "java.lang.NullPointerException"; SQL statement:
select distinct f1 from test [50000-0]
	at org.lealone.common.exceptions.DbException.convert(DbException.java:280)
	at org.lealone.net.TransferConnection.parseError(TransferConnection.java:76)
	at org.lealone.net.TcpClientConnection.handleResponse(TcpClientConnection.java:99)
	at org.lealone.net.TransferConnection.handle(TransferConnection.java:123)
	at org.lealone.net.nio.NioEventLoopAdapter.read(NioEventLoopAdapter.java:158)
Async callback is null, may be a bug! packetId = 50009
```

**Comment by codefollower** [comment]
我今天批量导数据时也遇到了，可能是最近加的新代码引发的bug，org.lealone.test.client.BatchTest 也跑不通了
正在修复中。
