### ISSUE TITLE
再次启动lealone报错

### ISSUE THREAD

**Issue by gongsongping** [lealone/Lealone#125]
第一次输入lealone启动以后, control+c退出, 再次lealone启动就会报错. 必须删除data里的数据才能重新启动成功.试了几次都是这样,不知道是不是我哪里设置不对?
报错log信息:
D:\lealone\Lealone\target\lealone-5.0.0\bin>lealone
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  22:33:39.387 Lealone version: 5.0.0-SNAPSHOT
INFO  22:33:39.398 Loading config from file:/D:/lealone/Lealone/target/lealone-5.0.0/conf/lealone.yaml
INFO  22:33:39.489 Base dir: ../data
INFO  22:33:39.498 Init storage engines: 6 ms
INFO  22:33:39.550 Init transaction engines: 51 ms
INFO  22:33:39.556 Init sql engines: 4 ms
INFO  22:33:39.717 Init protocol server engines: 159 ms
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.lealone.main.Lealone.init(Lealone.java:123)
        at org.lealone.main.Lealone.run(Lealone.java:64)
        at org.lealone.main.Lealone.main(Lealone.java:45)
Caused by: org.lealone.common.exceptions.DbException: General error: "java.lang.IllegalArgumentException: Illegal Capacity: -1" [50000-0]
        at org.lealone.common.exceptions.DbException.get(DbException.java:161)
        at org.lealone.common.exceptions.DbException.convert(DbException.java:292)
        at org.lealone.db.Database.openDatabase(Database.java:516)
        at org.lealone.db.Database.init(Database.java:426)
        at org.lealone.db.LealoneDatabase.<init>(LealoneDatabase.java:54)
        at org.lealone.db.LealoneDatabase.<clinit>(LealoneDatabase.java:32)
        ... 3 more
Caused by: org.lealone.common.exceptions.JdbcSQLException: General error: "java.lang.IllegalArgumentException: Illegal Capacity: -1" [50000-0]
        at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:340)    
        ... 9 more
Caused by: java.lang.IllegalArgumentException: Illegal Capacity: -1
        at java.base/java.util.ArrayList.<init>(ArrayList.java:160)
        at org.lealone.storage.aose.btree.BTreePage.readReplicationHostIds(BTreePage.java:639)    
        at org.lealone.storage.aose.btree.BTreeLeafPage.readRowStorage(BTreeLeafPage.java:252)    
        at org.lealone.storage.aose.btree.BTreeLeafPage.read(BTreeLeafPage.java:231)
        at org.lealone.storage.aose.btree.BTreePage.read(BTreePage.java:516)
        at org.lealone.storage.aose.btree.BTreeStorage.readLocalPageSync(BTreeStorage.java:346)   
        at org.lealone.storage.aose.btree.BTreeStorage.readLocalPageAsync(BTreeStorage.java:298)  
        at org.lealone.storage.aose.btree.BTreeStorage.readPage(BTreeStorage.java:284)
        at org.lealone.storage.aose.btree.BTreeStorage.readPage(BTreeStorage.java:275)
        at org.lealone.storage.aose.btree.BTreeMap.<init>(BTreeMap.java:105)
        at org.lealone.storage.aose.btree.BTreeMapBuilder.openMap(BTreeMapBuilder.java:47)        
        at org.lealone.storage.aose.AOStorage.openMap(AOStorage.java:105)
        at org.lealone.storage.aose.AOStorage.openBTreeMap(AOStorage.java:91)
        at org.lealone.storage.aose.AOStorage.openMap(AOStorage.java:76)
        at org.lealone.storage.aose.AOStorage.openMap(AOStorage.java:70)
        at org.lealone.transaction.aote.AMTransaction.openMap(AMTransaction.java:192)
        at org.lealone.transaction.aote.AMTransaction.openMap(AMTransaction.java:32)
        at org.lealone.db.index.standard.StandardPrimaryIndex.<init>(StandardPrimaryIndex.java:86)        at org.lealone.db.table.StandardTable.<init>(StandardTable.java:99)
        at org.lealone.db.schema.Schema.createTable(Schema.java:723)
        at org.lealone.db.Database.openMetaTable(Database.java:539)
        at org.lealone.db.Database.openDatabase(Database.java:497)
        ... 6 more

**Comment by codefollower** [comment]
是我前天修改的代码引起新 bug 了，正在修复，感谢报告问题。

**Comment by codefollower** [comment]
更新一下最新代码，然后删除 data 目录重试就可以了。
