### ISSUE TITLE
批量插入数据后, 重新启动, 表被删除, 执行sql报错

### ISSUE THREAD

**Issue by gongsongping** [lealone/Lealone#128]
我批量插入50万条数据, 成功了, 然后在终端ctrl+c退出, 再次lealone启动成功, 但是执行User.dao.findCount() 时报错. 应该是之前建的user表被删除了, runSqlScript重建表也报错, 必须把data文件夹里的数据删除后runSqlScript才成功
报错log信息:
INFO  [TcpServer-ShutdownHook-3] [2021-12-12T12:40:28,665] [TcpServerAccepter.java] Stopping tcp server accepter
INFO  [TcpServer-ShutdownHook-3] [2021-12-12T12:40:28,671] [Lealone.java] TcpServer stopped
INFO  [main] [2021-12-12T12:40:34,749] [Lealone.java] Lealone version: 5.0.0-SNAPSHOT
INFO  [main] [2021-12-12T12:40:34,762] [YamlConfigLoader.java] Loading config from file:/D:/lealone/hll/target/hll-1.0.0/conf/lealone.yaml
INFO  [main] [2021-12-12T12:40:34,863] [Lealone.java] Base dir: ../data
INFO  [main] [2021-12-12T12:40:34,874] [Lealone.java] Init storage engines: 8 ms
INFO  [main] [2021-12-12T12:40:34,946] [Lealone.java] Init transaction engines: 70 ms
INFO  [main] [2021-12-12T12:40:34,952] [Lealone.java] Init sql engines: 4 ms
INFO  [main] [2021-12-12T12:40:35,152] [Lealone.java] Init protocol server engines: 198 ms
INFO  [main] [2021-12-12T12:40:35,278] [Lealone.java] Init lealone database: 125 ms
INFO  [main] [2021-12-12T12:40:35,279] [TcpServerAccepter.java] Starting tcp server accepter
INFO  [TcpServerAccepter-9210] [2021-12-12T12:40:35,283] [Lealone.java] TcpServer started, host: 127.0.0.1, port: 9210
INFO  [vert.x-eventloop-thread-0] [2021-12-12T12:40:35,800] [HttpServer.java] Web root: ../web
INFO  [vert.x-eventloop-thread-0] [2021-12-12T12:40:35,802] [HttpServer.java] Sockjs path: /_lealone_sockjs_/*
INFO  [vert.x-eventloop-thread-0] [2021-12-12T12:40:35,803] [HttpServer.java] HttpServer is now listening on port: 9000
INFO  [TcpServerAccepter-9210] [2021-12-12T12:40:35,804] [Lealone.java] HttpServer started, host: 127.0.0.1, port: 9000
INFO  [TcpServerAccepter-9210] [2021-12-12T12:40:35,805] [Lealone.java] Total time: 1051 ms (Load config: 109 ms, Init: 416 ms, Start: 526 ms)
INFO  [TcpServerAccepter-9210] [2021-12-12T12:40:35,806] [Lealone.java] Exit with Ctrl+C
INFO  [vert.x-eventloop-thread-0] [2021-12-12T12:40:40,365] [HttpServiceHandler.java] execute service: hll.public.user_service.find_count
ERROR [vert.x-eventloop-thread-0] [2021-12-12T12:40:40,397] [HttpServiceHandler.java] failed to execute service: hll.public.user_service.find_count, cause: General error: "java.lang.NullPointerException: Cannot invoke ""java.lang.Integer.intValue()"" because the return value of ""java.util.HashMap.get(Object)"" is null" [50000-0]
org.lealone.common.exceptions.DbException: General error: "java.lang.NullPointerException: Cannot invoke ""java.lang.Integer.intValue()"" because the return value of ""java.util.HashMap.get(Object)"" is null" [50000-0]
	at org.lealone.common.exceptions.DbException.get(DbException.java:161) ~[hll-1.0.0.jar:?]
	at org.lealone.common.exceptions.DbException.convert(DbException.java:292) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.executor.YieldableBase.handleException(YieldableBase.java:162) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.executor.YieldableBase.run(YieldableBase.java:115) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.StatementBase.syncExecute(StatementBase.java:532) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.StatementBase.executeUpdate(StatementBase.java:629) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.StatementBase.executeUpdate(StatementBase.java:595) ~[hll-1.0.0.jar:?]
	at org.lealone.db.MetaRecord.execute(MetaRecord.java:64) ~[hll-1.0.0.jar:?]
	at org.lealone.db.Database.openMetaTable(Database.java:563) ~[hll-1.0.0.jar:?]
	at org.lealone.db.Database.openDatabase(Database.java:497) ~[hll-1.0.0.jar:?]
	at org.lealone.db.Database.init(Database.java:426) ~[hll-1.0.0.jar:?]
	at org.lealone.db.service.Service.getService(Service.java:89) ~[hll-1.0.0.jar:?]
	at org.lealone.db.service.Service.execute(Service.java:128) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpServiceHandler.executeService(HttpServiceHandler.java:113) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpServiceHandler.executeService(HttpServiceHandler.java:76) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpRouterFactory.handleHttpServiceRequest(HttpRouterFactory.java:113) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpRouterFactory.lambda$0(HttpRouterFactory.java:103) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1104) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:131) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:290) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:86) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:565) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:548) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71) [hll-1.0.0.jar:?]
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:189) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:179) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:159) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:147) [hll-1.0.0.jar:?]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155) [hll-1.0.0.jar:?]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [hll-1.0.0.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [hll-1.0.0.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [hll-1.0.0.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [hll-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.lealone.common.exceptions.JdbcSQLException: General error: "java.lang.NullPointerException: Cannot invoke ""java.lang.Integer.intValue()"" because the return value of ""java.util.HashMap.get(Object)"" is null"; SQL statement:
CREATE CACHED TABLE PUBLIC.USER(
    NAME VARCHAR,
    AGE INT
) PARAMETERS(ISSHARDINGMODE='false')
PACKAGE 'my.lealone.app.hll.dal.model'
GENERATE CODE '../hll-dal/src/main/java' [50000-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:340) ~[hll-1.0.0.jar:?]
	... 62 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at org.lealone.storage.aose.btree.BTreeChunk.getPageLength(BTreeChunk.java:67) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.btree.BTreeStorage.readLocalPageSync(BTreeStorage.java:345) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.btree.BTreeStorage.readLocalPageAsync(BTreeStorage.java:298) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.btree.BTreeStorage.readPage(BTreeStorage.java:284) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.btree.BTreeStorage.readPage(BTreeStorage.java:275) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.btree.BTreeMap.<init>(BTreeMap.java:105) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.btree.BTreeMapBuilder.openMap(BTreeMapBuilder.java:47) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.AOStorage.openMap(AOStorage.java:105) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.AOStorage.openBTreeMap(AOStorage.java:91) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.AOStorage.openMap(AOStorage.java:76) ~[hll-1.0.0.jar:?]
	at org.lealone.storage.aose.AOStorage.openMap(AOStorage.java:70) ~[hll-1.0.0.jar:?]
	at org.lealone.transaction.aote.AMTransaction.openMap(AMTransaction.java:195) ~[hll-1.0.0.jar:?]
	at org.lealone.transaction.aote.AMTransaction.openMap(AMTransaction.java:1) ~[hll-1.0.0.jar:?]
	at org.lealone.db.index.standard.StandardPrimaryIndex.<init>(StandardPrimaryIndex.java:86) ~[hll-1.0.0.jar:?]
	at org.lealone.db.table.StandardTable.<init>(StandardTable.java:99) ~[hll-1.0.0.jar:?]
	at org.lealone.db.schema.Schema.createTable(Schema.java:723) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.ddl.CreateTable.update(CreateTable.java:159) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.executor.DefaultYieldableLocalUpdate.executeInternal(DefaultYieldableLocalUpdate.java:22) ~[hll-1.0.0.jar:?]
	at org.lealone.sql.executor.YieldableBase.run(YieldableBase.java:109) ~[hll-1.0.0.jar:?]
	... 58 more
INFO  [vert.x-eventloop-thread-0] [2021-12-12T12:43:58,119] [HttpServiceHandler.java] execute service: hll.public.user_service.find_count
ERROR [vert.x-eventloop-thread-0] [2021-12-12T12:43:58,120] [HttpServiceHandler.java] failed to execute service: hll.public.user_service.find_count, cause: service USER_SERVICE not found
java.lang.RuntimeException: service USER_SERVICE not found
	at org.lealone.db.service.Service.getService(Service.java:98) ~[hll-1.0.0.jar:?]
	at org.lealone.db.service.Service.execute(Service.java:128) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpServiceHandler.executeService(HttpServiceHandler.java:113) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpServiceHandler.executeService(HttpServiceHandler.java:76) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpRouterFactory.handleHttpServiceRequest(HttpRouterFactory.java:113) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpRouterFactory.lambda$0(HttpRouterFactory.java:103) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1104) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:131) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:290) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:86) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:565) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:548) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71) [hll-1.0.0.jar:?]
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:189) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:179) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:159) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:147) [hll-1.0.0.jar:?]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155) [hll-1.0.0.jar:?]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [hll-1.0.0.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [hll-1.0.0.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [hll-1.0.0.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [hll-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
INFO  [vert.x-eventloop-thread-0] [2021-12-12T12:45:55,202] [HttpServiceHandler.java] execute service: hll.public.user_service.find_count
ERROR [vert.x-eventloop-thread-0] [2021-12-12T12:45:55,203] [HttpServiceHandler.java] failed to execute service: hll.public.user_service.find_count, cause: service USER_SERVICE not found
java.lang.RuntimeException: service USER_SERVICE not found
	at org.lealone.db.service.Service.getService(Service.java:98) ~[hll-1.0.0.jar:?]
	at org.lealone.db.service.Service.execute(Service.java:128) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpServiceHandler.executeService(HttpServiceHandler.java:113) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpServiceHandler.executeService(HttpServiceHandler.java:76) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpRouterFactory.handleHttpServiceRequest(HttpRouterFactory.java:113) ~[hll-1.0.0.jar:?]
	at org.lealone.server.http.HttpRouterFactory.lambda$0(HttpRouterFactory.java:103) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1104) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:131) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:290) ~[hll-1.0.0.jar:?]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:86) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:565) ~[hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:548) ~[hll-1.0.0.jar:?]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71) [hll-1.0.0.jar:?]
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:189) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:179) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:159) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:147) [hll-1.0.0.jar:?]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155) [hll-1.0.0.jar:?]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [hll-1.0.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61) [hll-1.0.0.jar:?]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [hll-1.0.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [hll-1.0.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [hll-1.0.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [hll-1.0.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [hll-1.0.0.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [hll-1.0.0.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [hll-1.0.0.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [hll-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by codefollower** [comment]
同步一下 lealone 最新的代码试试，我创建了一个微服务应用，通过 lealone orm 写入和查询数据，退出重启了多次没有重现出问题。
