### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by HUANGLIURU** [lealone/Lealone#142]
不好重现，看日志发现的，lealone长时间运行就会出现一些奇怪问题，数据库会损坏没法再用。

java.lang.NullPointerException: Cannot read field "page" because the return value of "org.lealone.storage.aose.btree.BTreePage.getParentRef()" is null
        at org.lealone.storage.aose.btree.PageOperations$AddChild.insertChildren(PageOperations.java:407) ~[app-1.0.0.jar:1.0.0]
        at org.lealone.storage.aose.btree.PageOperations$AddChild.run(PageOperations.java:393) ~[app-1.0.0.jar:1.0.0]
        at org.lealone.storage.PageOperation.run(PageOperation.java:40) ~[app-1.0.0.jar:1.0.0]
        at org.lealone.storage.DefaultPageOperationHandler.runTasks(DefaultPageOperationHandler.java:120) ~[app-1.0.0.jar:1.0.0]
        at org.lealone.storage.DefaultPageOperationHandler.run(DefaultPageOperationHandler.java:103) ~[app-1.0.0.jar:1.0.0]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by codefollower** [comment]
感谢报告问题，正在排查原因。
