### ISSUE TITLE
Wrong user name or password

### ISSUE THREAD

**Issue by HUANGLIURU** [lealone/Lealone#150]
org.lealone.common.exceptions.DbException: Wrong user name or password [28000-0]
	at org.lealone.common.exceptions.DbException.get(DbException.java:172) ~[lealone-common-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.common.exceptions.DbException.get(DbException.java:149) ~[lealone-common-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.common.exceptions.DbException.get(DbException.java:138) ~[lealone-common-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.db.session.ServerSessionFactory.createServerSession(ServerSessionFactory.java:100) ~[lealone-db-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.db.session.ServerSessionFactory.createServerSession(ServerSessionFactory.java:48) ~[lealone-db-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.db.session.ServerSessionFactory.createSession(ServerSessionFactory.java:39) ~[lealone-db-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.db.session.SessionFactory.createSession(SessionFactory.java:31) ~[lealone-common-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.orm.ModelTable.bindTable(ModelTable.java:70) ~[lealone-orm-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.orm.ModelTable.getDatabase(ModelTable.java:53) ~[lealone-orm-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.orm.Model.getExpressionColumn(Model.java:330) ~[lealone-orm-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.orm.ExpressionBuilder.createComparison(ExpressionBuilder.java:90) ~[lealone-orm-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.orm.ExpressionBuilder.setRootExpression(ExpressionBuilder.java:112) ~[lealone-orm-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.orm.ExpressionBuilder.eq(ExpressionBuilder.java:130) ~[lealone-orm-5.0.0-SNAPSHOT.jar:na]
	at org.lealone.orm.property.PBaseValueEqual.eq(PBaseValueEqual.java:31) ~[lealone-orm-5.0.0-SNAPSHOT.jar:na]

**Comment by codefollower** [comment]
嵌入式场景，如果 jdbc url 里指定的数据库不存在，会自动创建它，
如果没有传递用户名和密码，默认用户名是 root，密码是空的。

出现这个异常，需要看看那个 Model 子类对应的数据库名是否跟 jdbc url 里指定的数据库一样。

如果你是用 create-lealone-app-5.0.0 创建的微服务应用，
检查一下 xxx-test\src\test\resources\lealone.yaml 的 jdbc_url 参数是否跟 xxx-main\src\main\java\------\main\XxxSqlScript.java 里的 runScript 中的 jdbcUrl 一样。

如果都不是，把数据目录删除重新建表，再跑一下试试。

**Comment by HUANGLIURU** [comment]
解决了，谢谢。是用create-lealone-app-5.0.0 创建的。
把xxx-test\src\test\resources\lealone.yaml 的 jdbc_url “jdbc:lealone:embed:xxx” 换成了 “jdbc:lealone:tcp://localhost/xxx?user=root&password=”就好了
