### ISSUE TITLE
Cannot enter synchronized block because "this.infoSchema" is null

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#197]
Connected to the target VM, address: '127.0.0.1:5676', transport: 'socket'
10:42:45.146 [Thread-0] INFO org.lealone.main.Lealone -- Lealone version: 5.2.0-SNAPSHOT
10:42:45.153 [Thread-0] INFO org.lealone.main.config.YamlConfigLoader -- Loading config from file:/D:/java/dmy-sc/sc-admin-starter/target/classes/lealone.yaml
10:42:45.202 [Thread-0] INFO org.lealone.main.Lealone -- Base dir: D:/java/dmy-sc/db
10:42:45.207 [Thread-0] INFO org.lealone.main.Lealone -- Init storage engines: 2 ms
10:42:45.228 [Thread-0] INFO org.lealone.main.Lealone -- Init transaction engines: 21 ms
10:42:45.230 [Thread-0] INFO org.lealone.main.Lealone -- Init sql engines: 1 ms
10:42:45.286 [Thread-0] INFO org.lealone.main.Lealone -- Init protocol server engines: 56 ms
10:42:45.370 [Thread-0] INFO org.lealone.main.Lealone -- Init lealone database: 84 ms
10:42:45.371 [Thread-0] INFO org.lealone.net.nio.ServerAccepter -- Starting TcpServer accepter
10:42:45.371 [Thread-0] INFO org.lealone.main.Lealone -- TcpServer started, host: 0.0.0.0, port: 8101
10:42:45.372 [Thread-0] INFO org.lealone.main.Lealone -- Total time: 224 ms (Load config: 54 ms, Init: 168 ms, Start: 2 ms)
10:42:45.372 [Thread-0] INFO org.lealone.main.Lealone -- Exit with Ctrl+C
10:42:45.372 [CheckpointService] ERROR org.lealone.transaction.aote.AOTransactionEngine -- Failed to execute gc
java.lang.NullPointerException: Cannot enter synchronized block because "this.infoSchema" is null
	at org.lealone.db.Database.initInfoSchemaMetaTables(Database.java:637)
	at org.lealone.db.Database.getAllSchemas(Database.java:1310)
	at org.lealone.db.Database.getAllSchemas(Database.java:1305)
	at org.lealone.db.LealoneDatabase.gc(LealoneDatabase.java:142)
	at org.lealone.transaction.aote.AOTransactionEngine.executeGcTasks(AOTransactionEngine.java:269)
	at org.lealone.transaction.aote.AOTransactionEngine.gc(AOTransactionEngine.java:257)
	at org.lealone.transaction.aote.AOTransactionEngine.access$500(AOTransactionEngine.java:38)
	at org.lealone.transaction.aote.AOTransactionEngine$CheckpointService.run(AOTransactionEngine.java:410)
	at org.lealone.main.Lealone.run(Lealone.java:175)
	at org.lealone.main.Lealone.start(Lealone.java:111)
	at org.lealone.main.Lealone.lambda$main$0(Lealone.java:52)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-10 10:42:45 database: opening SC_WMS (build 0) (persistent: true)
2023-08-10 10:42:45 database: opened SC_WMS

启动的时候报错。不影响使用。最新版

**Comment by codefollower** [comment]
bug 修复了，感谢报告问题。
