### ISSUE TITLE
mysql function `SELECT GET_LOCK('airflow_MIGRATIONS', 1800)`

### ISSUE THREAD

**Issue by wtog** [lealone/Lealone#220]
## lealone version

6.0.0-SNAPSHOT

## sql in mysql

`SELECT GET_LOCK('airflow_MIGRATIONS', 1800)`

## lealone error

```
org.lealone.common.exceptions.JdbcSQLException: Function "GET_LOCK" not found; SQL statement:
SELECT GET_LOCK('airflow_MIGRATIONS', 1800) [90022-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:342)
	at org.lealone.common.exceptions.DbException.get(DbException.java:173)
	at org.lealone.common.exceptions.DbException.get(DbException.java:150)
	at org.lealone.sql.SQLParserBase.readJavaFunction(SQLParserBase.java:2270)
	at org.lealone.sql.SQLParserBase.readFunction(SQLParserBase.java:2327)
	at org.lealone.sql.SQLParserBase.readTerm(SQLParserBase.java:2654)
	at org.lealone.sql.SQLParserBase.readFactor(SQLParserBase.java:2184)
	at org.lealone.sql.SQLParserBase.readSum(SQLParserBase.java:2171)
	at org.lealone.sql.SQLParserBase.readConcat(SQLParserBase.java:2144)
	at org.lealone.sql.SQLParserBase.readCondition(SQLParserBase.java:2008)
	at org.lealone.sql.SQLParserBase.readAnd(SQLParserBase.java:1989)
	at org.lealone.sql.SQLParserBase.readExpression(SQLParserBase.java:1981)
	at org.lealone.sql.SQLParserBase.parseSelectSimpleSelectPart(SQLParserBase.java:1708)
	at org.lealone.sql.SQLParserBase.parseSelectSimple(SQLParserBase.java:1531)
	at org.lealone.sql.SQLParserBase.parseSelectSub(SQLParserBase.java:1508)
	at org.lealone.sql.SQLParserBase.parseSelectUnion(SQLParserBase.java:1478)
	at org.lealone.sql.SQLParserBase.parseSelect(SQLParserBase.java:1466)
	at org.lealone.sql.SQLParserBase.parseStatement(SQLParserBase.java:455)
	at org.lealone.sql.SQLParserBase.parse(SQLParserBase.java:327)
	at org.lealone.sql.SQLParserBase.parse(SQLParserBase.java:285)
	at org.lealone.sql.SQLParserBase.parse(SQLParserBase.java:1)
	at org.lealone.db.session.ServerSession.prepareStatement(ServerSession.java:476)
	at org.lealone.plugins.mysql.server.MySQLServerConnection.prepareStatement(MySQLServerConnection.java:186)
	at org.lealone.plugins.mysql.server.MySQLServerConnection.executeStatement(MySQLServerConnection.java:205)
	at org.lealone.plugins.mysql.server.handler.CommandPacketHandler.handle(CommandPacketHandler.java:37)
	at org.lealone.plugins.mysql.server.MySQLServerConnection.handle(MySQLServerConnection.java:388)
	at org.lealone.net.nio.NioEventLoop.read(NioEventLoop.java:275)
	at org.lealone.net.nio.NioEventLoop.handleSelectedKeys(NioEventLoop.java:492)
	at org.lealone.net.NetScheduler.runEventLoop(NetScheduler.java:62)
	at org.lealone.server.scheduler.GlobalScheduler.run(GlobalScheduler.java:70)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by codefollower** [comment]
GET_LOCK 这个函数还没有实现。
