### ISSUE TITLE
Failed to handle packet, packetId: 626, 

### ISSUE THREAD

**Issue by cbqqkcel** [lealone/Lealone#246]
22:33:53.448 [ScheduleService-6] ERROR com.lealone.server.scheduler.PacketHandleTask - Failed to handle packet, packetId: 626, packetType: PREPARED_STATEMENT_PREPARE, sessionId: 1
com.lealone.common.exceptions.JdbcSQLException: Column "TaskLog.taskId" not found [42122-0]
	at com.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:342) ~[lealone-common-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.common.exceptions.DbException.get(DbException.java:173) ~[lealone-common-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.common.exceptions.DbException.get(DbException.java:150) ~[lealone-common-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.sql.expression.ExpressionColumn.optimize(ExpressionColumn.java:182) ~[lealone-sql-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.sql.expression.condition.Comparison.optimize(Comparison.java:179) ~[lealone-sql-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.sql.query.Select.prepare(Select.java:387) ~[lealone-sql-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.db.session.ServerSession.prepareStatement(ServerSession.java:492) ~[lealone-db-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.server.handler.PreparedStatementPacketHandlers.prepareStatement(PreparedStatementPacketHandlers.java:37) ~[lealone-server-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.server.handler.PreparedStatementPacketHandlers.access$600(PreparedStatementPacketHandlers.java:24) ~[lealone-server-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.server.handler.PreparedStatementPacketHandlers$Prepare.handle(PreparedStatementPacketHandlers.java:46) ~[lealone-server-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.server.handler.PreparedStatementPacketHandlers$Prepare.handle(PreparedStatementPacketHandlers.java:43) ~[lealone-server-6.1.0-SNAPSHOT.jar:?]
	at com.lealone.server.handler.PacketHandler.handle(PacketHandler.java:19) ~[lealone-server-6.1.0-SNAPSHOT.jar:?]

TaskLog taskId 是有这个字段的，代码是最新的。

**Comment by codefollower** [comment]
6.1.0-SNAPSHOT 还有很多 bug，代码实现改动挺大。
如果你只是测功能，还是建议你先拿6.0.1来测。

**Comment by codefollower** [comment]
6.1.0-SNAPSHOT 还有很多 bug，代码实现改动挺大。
如果你只是测功能，还是建议你先拿6.0.1来测。
