### ISSUE TITLE
max/min bug? 

### ISSUE THREAD

**Issue by mervynzhang** [lealone/Lealone#247]
最新代码， max/min一个 INTEGER 字段的时候报错了， max/min  VARCHAR 字段没报错， 老版本没报错。

```
sql> select max(CUST_ID) from CUSTOMER;
Error: General error: "java.lang.ClassCastException: class com.lealone.db.row.Row cannot be cast to class com.lealone.db.value.Value (com.lealone.db.row.Row and com.lealone.db.value.Value are in unnamed module of loader 'app')"; SQL statement:
select max(CUST_ID) from CUSTOMER [50000-0]

sql> select (CUST_ID) from CUSTOMER;    
+---------+
| CUST_ID |
+---------+
| 1       |
| 2       |

...
sql> select count(CUST_ID) from CUSTOMER; 
+----------------+
| COUNT(CUST_ID) |
+----------------+
| 6              |
+----------------+
(1 row, 2 ms)

sql> select min(name) from CUSTOMER;      
+-----------+
| MIN(NAME) |
+-----------+
| John      |
+-----------+

**Comment by mervynzhang** [comment]
client退出的时候， server端刷屏报下边的错
![image](https://github.com/user-attachments/assets/9338edfa-b48d-4b78-bf83-e6871a23c80a)


```
16:06:19.583 [ScheduleService-7] WARN  com.lealone.net.nio.NioEventLoop - Failed to read remote address[127.0.0.1:49679]: Connection reset
16:06:19.584 [ScheduleService-7] WARN  com.lealone.server.scheduler.GlobalScheduler - Failed to runEventLoop
java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.limit()" because "this.buff" is null
        at com.lealone.db.DataBuffer.clear(DataBuffer.java:496) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.net.NetBuffer.reset(NetBuffer.java:87) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.net.NetBuffer.recycle(NetBuffer.java:81) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.net.TransferInputStream.closeForce(TransferInputStream.java:115) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.server.TcpServerConnection.close(TcpServerConnection.java:222) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.server.AsyncServer.removeConnection(AsyncServer.java:133) ~[lealone-6.1.0-SNAPSHOT.ja        at com.lealone.server.TcpServerConnection.handleException(TcpServerConnection.java:65) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.net.nio.NioEventLoop.handleException(NioEventLoop.java:540) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.net.nio.NioEventLoop.handleReadException(NioEventLoop.java:527) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.net.nio.NioEventLoop.read(NioEventLoop.java:221) ~[lealone-6.1.0-SNAPSHOT.jar:?]     
        at com.lealone.net.nio.NioEventLoop.handleSelectedKeys(NioEventLoop.java:465) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.net.nio.NioEventLoop.handleSelectedKeys(NioEventLoop.java:450) ~[lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.server.scheduler.GlobalScheduler.runEventLoop(GlobalScheduler.java:441) [lealone-6.1.0-SNAPSHOT.jar:?]
        at com.lealone.server.scheduler.GlobalScheduler.run(GlobalScheduler.java:75) [lealone-6.1.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by codefollower** [comment]
lealone-6.1.0-SNAPSHOT 的代码还在快速迭代中，还没有稳定

**Comment by mervynzhang** [comment]
给BTreeCursor的getKey 加了几个println , 看起来key 和 value 一样？ 
https://github.com/lealone/Lealone/blob/master/lealone-aose/src/main/java/com/lealone/storage/aose/btree/BTreeCursor.java#L38
```
    public K getKey() {
        System.out.println(key);
        System.out.println(value);
        System.out.println("pos.index=" + pos.index);
        return key;
    }
```
```
( /* key:6 */ 6, 9, 'CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_5 ON PUBLIC.CUSTOMER(CUST_ID)')
( /* key:6 */ 6, 9, 'CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_5 ON PUBLIC.CUSTOMER(CUST_ID)')
pos.index=6
( /* key:7 */ 7, 12, 'ALTER TABLE PUBLIC.CUSTOMER ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(CUST_ID) INDEX PUBLIC.PRIMARY_KEY_5')
( /* key:7 */ 7, 12, 'ALTER TABLE PUBLIC.CUSTOMER ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(CUST_ID) INDEX PUBLIC.PRIMARY_KEY_5')
pos.index=7
```

**Comment by codefollower** [comment]
> 给BTreeCursor的getKey 加了几个println , 看起来key 和 value 一样？ https://github.com/lealone/Lealone/blob/master/lealone-aose/src/main/java/com/lealone/storage/aose/btree/BTreeCursor.java#L38
>

最新版本的 RowPage 存放的只有 Row 对象，key 和 value 都是 Row。
上层在使用 RowPage 的数据时会自己从 Row 对象获取对应的 key。

单独使用存储引擎读写数据时，数据才会用 KeyValuePage 存放。

**Comment by mervynzhang** [comment]
> > 给BTreeCursor的getKey 加了几个println , 看起来key 和 value 一样？ https://github.com/lealone/Lealone/blob/master/lealone-aose/src/main/java/com/lealone/storage/aose/btree/BTreeCursor.java#L38
> 
> 最新版本的 RowPage 存放的只有 Row 对象，key 和 value 都是 Row。 上层在使用 RowPage 的数据时会自己从 Row 对象获取对应的 key。
> 
> 单独使用存储引擎读写数据时，数据才会用 KeyValuePage 存放。

我的意思是max/min的bug 是这个引起的吧？

**Comment by codefollower** [comment]
最新的代码我测试了，max/min 已经正常了。

**Comment by codefollower** [comment]
> 最新的代码我测试了，max/min 已经正常了。

我明白了，我测试的是普通索引，不是 primary key，primary key 确实还有 bug。

**Comment by codefollower** [comment]
已经修复，感谢报告 bug。
