### ISSUE TITLE
可以替代👌

### ISSUE THREAD

**Issue by jerdbo** [lealone/Lealone#249]

**Comment by codefollower** [comment]
把 **jdbc:h2:~/test** 替换成 **jdbc:lealone:embed:test**

参考文档 [通过嵌入模式使用Lealone数据库](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E9%80%9A%E8%BF%87%E5%B5%8C%E5%85%A5%E6%A8%A1%E5%BC%8F%E4%BD%BF%E7%94%A8Lealone%E6%95%B0%E6%8D%AE%E5%BA%93.md)

**Comment by jerdbo** [comment]
url: jdbc:lealone:embed::pipeline_management;persistent=false;MODE=MYSQL 
 如果指定 mode 会报下面错误：
2024-11-28 11:04:07.247  WARN [,,,] 14922 --- [heduleService-0] c.l.db.scheduler.EmbeddedScheduler       : Failed to run misc task: com.lealone.db.session.ServerSessionFactory$$Lambda$987/0x0000000800aeb028@583ac952

java.lang.NullPointerException: null
        at com.lealone.db.auth.PasswordHash.validateUserPasswordHashMySQL(PasswordHash.java:102)
        at com.lealone.db.auth.PasswordHash.validateUserPasswordHash(PasswordHash.java:68)
        at com.lealone.db.auth.User.validateUserPasswordHash(User.java:243)
        at com.lealone.db.session.ServerSessionFactory.validateUser(ServerSessionFactory.java:113)
        at com.lealone.db.session.ServerSessionFactory.createServerSession(ServerSessionFactory.java:80)
        at com.lealone.db.session.ServerSessionFactory.lambda$createSession$0(ServerSessionFactory.java:38)
        at com.lealone.db.scheduler.SchedulerBase.runMiscTasks(SchedulerBase.java:216)
        at com.lealone.db.scheduler.EmbeddedScheduler.runMiscTasks(EmbeddedScheduler.java:57)
        at com.lealone.db.scheduler.EmbeddedScheduler.run(EmbeddedScheduler.java:63)
        at java.lang.Thread.run(Thread.java:750)

**Comment by codefollower** [comment]
lealone-mysql 插件目前不支持嵌入模式，后续再看看怎么做合适。
